project:
  type: website
  output-dir: docs

website:
  title: "Siam Maksud"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/siam015
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

