project:
  type: website
  output-dir: docs

website:
  title: "Siam Maksud"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/siam015
      - icon: linkedin
        href: https://www.linkedin.com/in/siam-maksud-59780421a/
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

